services:
  - type: web
    name: signalml
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: gunicorn pygwalker_backend:app
    healthCheckPath: /health
    autoDeploy: true
